INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), 1, NULL, 'INTENTOS_BLOQUEO', '5', 'GENERAL', 'Num. intentos en los que se bloquea la contraseña');
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), 0, NULL, 'INTENTOS_BLOQUEO', '5', 'GENERAL', 'Num. intentos en los que se bloquea la contraseña');

ALTER TABLE UCCADUSER ADD LOGIN_ATTEMPTS Integer;
COMMIT;
UPDATE UCCADUSER SET LOGIN_ATTEMPTS = '0' WHERE LOGIN_ATTEMPTS IS NULL;

ALTER TABLE UCCADUSER ADD BLOQUEADO Varchar(1);
COMMIT;
UPDATE UCCADUSER SET BLOQUEADO = 'F' WHERE BLOQUEADO IS NULL;