--RADIOIBUSUARIOS
ALTER TABLE UCCADUSER ADD FECHA_PASSWORD TIMESTAMP;

--IBRADIO
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES ( gen_id(GENUID,1), 0, NULL, 'EXPIRACION_PASSWORD', '90', 'GENERAL', 'Dias renovación de la contraseña');
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES ( gen_id(GENUID,1), 1, NULL, 'EXPIRACION_PASSWORD', '90', 'GENERAL', 'Dias renovación de la contraseña');