INSERT INTO UCCADMENU (ID, IDUSER, DESCRIPCION, ICONO, IDPARENT, ORDEN, URL) VALUES(72, -2, 'Grupos', 'viewGrupos', 7, 2, '/Grupos');
INSERT INTO UCCADMENU (ID, IDUSER, DESCRIPCION, ICONO, IDPARENT, ORDEN, URL) VALUES(73, -2, 'Aparatos complejos', 'viewAparCompl', 7, 3, '/AparatosComplejos');

INSERT INTO UCCADMENUPERM (IDMENU, IDUSER) VALUES(72, 0);
INSERT INTO UCCADMENUPERM (IDMENU, IDUSER) VALUES(73, 0);

ALTER TABLE GAPARATOS ALTER COLUMN COD_GRUP TYPE VARCHAR(15);

SET TERM ^;
CREATE TRIGGER APARATOS_COMPLEJOS_BI FOR APARATOS_COMPLEJOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^


SET TERM ^;
CREATE TRIGGER GAPARATOS_BI FOR GAPARATOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^


SET TERM ^;
CREATE TRIGGER DAPARATOS_BI FOR DAPARATOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^


SET TERM ^;
CREATE TRIGGER APARATOS_BI FOR APARATOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^


SET TERM ^;
CREATE TRIGGER CONSUMIBLES_BI FOR CONSUMIBLES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^


SET TERM ^;
CREATE TRIGGER CONS_GRUPO_BI FOR CONS_GRUPO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    if (new.OID is null) then new.OID = gen_id(GENUID,1);
END^
SET TERM ;^



CREATE OR ALTER VIEW FK_CHECK AS 
SELECT a.TABLE_NAME AS TABLA, b.TABLE_NAME AS DEPENDENCIA, r.FIELD_RELATED, r.DELETE_RULE
FROM relation_def r
INNER JOIN class_def a ON r.FROM_CID = a.CID
INNER JOIN class_def b ON r.TO_CID = b.CID;