INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpServer', 'smtp.serviciodecorreo.es', 'MAIL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpMail', 'no-reply@grupmanchon.com', 'MAIL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpUser', 'no-reply@grupmanchon.com', 'MAIL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpPort', '465', 'MAIL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpPassword', 'Manchon2021', 'MAIL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'smtpusessl', 'true', 'MAIL', NULL);

UPDATE WEBCONFIG SET 
OID = '17569808', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpServer', 
VALOR = 'smtp.serviciodecorreo.es', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569808';

UPDATE WEBCONFIG SET 
OID = '17569809', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpMail', 
VALOR = 'no-reply@grupmanchon.com', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569809';

UPDATE WEBCONFIG SET 
OID = '17569810', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpUser', 
VALOR = 'no-reply@grupmanchon.com', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569810';

UPDATE WEBCONFIG SET 
OID = '17569811', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpPort', 
VALOR = '465', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569811';

UPDATE WEBCONFIG SET 
OID = '17569812', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpPassword', 
VALOR = 'Manchon2021', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569812';

UPDATE WEBCONFIG SET 
OID = '17569813', 
VERS = '1', 
OWNER = NULL, 
CLAVE = 'smtpusessl', 
VALOR = 'true', 
SECCION = 'MAIL', 
DESCRIPCION = NULL
WHERE OID = '17569813';

COMMIT;
