INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '1', NULL, 'ENDPOINTARCHIVO', 'https://www.alhmedcom2.net/GSHAPI/Mensajes/Enviar_Archivo', 'GENERAL', NULL);
INSERT INTO WEBCONFIG (OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION) VALUES (gen_id(GENUID,1), '0', NULL, 'ENDPOINTARCHIVO', 'https://www.alhmedcom2.net/GSHAPI/Mensajes/Enviar_Archivo', 'GENERAL', NULL);

COMMIT;
