INSERT INTO VID_PREGUNTAS
(OID, VERS, CID, OWNER, IOR_CONSENTIMIENTO, NOMBRE, CANAL, BORRADO, MACRO, TIPO, CAMPO, MACRORESPUESTA, MACROCONDICION, ANULAPRUEBA, ENVIO_SMS, ENVIO_MAIL, ENVIO_RESULTADO, ENVIO_MEDIO)
VALUES(gen_id(GENUID,1), 2, null, 22628004, null, 'Está embarazada?', null, null, 'M_EMBARAZADA', 3, 'EMBARAZADA', null, NULL, null, null, null, null, null);

INSERT INTO VID_PREGUNTAS
(OID, VERS, CID, OWNER, IOR_CONSENTIMIENTO, NOMBRE, CANAL, BORRADO, MACRO, TIPO, CAMPO, MACRORESPUESTA, MACROCONDICION, ANULAPRUEBA, ENVIO_SMS, ENVIO_MAIL, ENVIO_RESULTADO, ENVIO_MEDIO)
VALUES(gen_id(GENUID,1), 2, null, 22627992, null, 'Està embarassada?', null, null, 'M_EMBARAZADA', 3, 'EMBARAZADA', null, NULL, null, null, null, null, null);

INSERT INTO VID_PREGUNTAS
(OID, VERS, CID, OWNER, IOR_CONSENTIMIENTO, NOMBRE, CANAL, BORRADO, MACRO, TIPO, CAMPO, MACRORESPUESTA, MACROCONDICION, ANULAPRUEBA, ENVIO_SMS, ENVIO_MAIL, ENVIO_RESULTADO, ENVIO_MEDIO)
VALUES(gen_id(GENUID,1), 2, null, 21654634, null, 'Està embarassada?', null, null, 'M_EMBARAZADA', 3, 'EMBARAZADA', null, NULL, null, null, null, null, null);

UPDATE VID_PREGUNTAS SET BORRADO = 'T' WHERE MACRO = 'M_EMBARAZO';