SET TERM ^ ;
CREATE  PROCEDURE HUECOSLIBRES_TUOTEMPO (
    OID_MUTUA INTEGER,
    FECHAINI TIMESTAMP,
    FECHAFIN TIMESTAMP,
    HORAMIN VARCHAR(5),
    HORAMAX VARCHAR(5),
    OID_GRUPO INTEGER,
    NUMERO_HUECOS INTEGER,
    OID_CENTRO INTEGER,
    OID_TIPOEXPLO INTEGER )
RETURNS (
    AVAILABILITY_LID VARCHAR(30),
    FECHA TIMESTAMP,
    START_TIME VARCHAR(5),
    END_TIME VARCHAR(5),
    LOCATION_LID INTEGER,
    RESOURCE_LID INTEGER,
    ACTIVITY_LID INTEGER,
    INSURANCE_LID INTEGER,
    CCANTIDAD NUMERIC(8,2),
    TEXTODEFECTO VARCHAR(40),
    HORARIO_APARATO VARCHAR(20) )
AS
DECLARE VARIABLE GRUPOEXP VARCHAR(6);
DECLARE VARIABLE APARATO INTEGER;
DECLARE CODHORARIO VARCHAR(20);
DECLARE HORARIO INTEGER;
DECLARE VARIABLE CODAPARATO VARCHAR(20);
DECLARE VARIABLE EXPLO VARCHAR(10);
DECLARE VARIABLE TIPOACTO INTEGER;
DECLARE VARIABLE FECHAF VARCHAR(20);
DECLARE VARIABLE HORA VARCHAR(5);
DECLARE VARIABLE DIASEMANA INTEGER;
DECLARE VARIABLE HHORA VARCHAR(5);
DECLARE VARIABLE APA1 VARCHAR(10);
DECLARE VARIABLE APA2 VARCHAR(10);
DECLARE VARIABLE APA3 VARCHAR(10);
DECLARE VARIABLE APA4 VARCHAR(10);
DECLARE VARIABLE APA5 VARCHAR(10);
DECLARE VARIABLE APA6 VARCHAR(10);
DECLARE VARIABLE COM1 VARCHAR(40);
DECLARE VARIABLE COM2 VARCHAR(40);
DECLARE VARIABLE COM3 VARCHAR(40);
DECLARE VARIABLE DIAFESTIVO TIMESTAMP;
DECLARE VARIABLE HTEXTODEFECTO VARCHAR(40);
DECLARE VARIABLE C1 VARCHAR(10);
DECLARE VARIABLE C2 VARCHAR(10);
DECLARE VARIABLE C3 VARCHAR(10);
DECLARE VARIABLE A VARCHAR(40);
DECLARE VARIABLE HORAANULADA VARCHAR(5);
DECLARE VARIABlE HORACAMBIADA VARCHAR(5);
DECLARE VARIABLE HORAOCUPADA VARCHAR(5);
DECLARE VARIABLE X INTEGER;
DECLARE VARIABLE VUELTA SMALLINT;
DECLARE VARIABLE FECHABUCLE TIMESTAMP;
DECLARE VARIABLE FECHAFINAL TIMESTAMP;
DECLARE VARIABLE TVUELTAS SMALLINT;
DECLARE VARIABLE APA VARCHAR(10);
DECLARE VARIABLE CANTIDAD NUMERIC(8,2);
DECLARE VARIABLE HAYHORAS VARCHAR(1);
DECLARE VARIABLE OID_APA INTEGER;
DECLARE VARIABLE FIL_APA VARCHAR(10);
DECLARE VARIABLE OID_APA1 INTEGER;
DECLARE VARIABLE FIL_APA1 VARCHAR(10);
DECLARE VARIABLE OID_APA2 INTEGER;
DECLARE VARIABLE FIL_APA2 VARCHAR(10);
DECLARE VARIABLE OID_APA3 INTEGER;
DECLARE VARIABLE FIL_APA3 VARCHAR(10);
DECLARE VARIABLE OID_APA4 INTEGER;
DECLARE VARIABLE FIL_APA4 VARCHAR(10);
DECLARE VARIABLE H2HORA VARCHAR(45);
DECLARE VARIABLE H3HORA VARCHAR(5);
BEGIN
 /*
 GRUPOEXP = TRIM(SUBSTRING(:CODIGOEXP FROM 1 For 3));
 EXPLO=SUBSTRING(:CODIGOEXP FROM 4 For 4);
  
 if (GRUPOEXP = 'DEN') THEN TIPOACTO = 1;
 ELSE if (GRUPOEXP = 'TAC') then TipoActo = 2;
 ELSE if (GRUPOEXP = 'RX ') then TipoActo = 3;
 ELSE if (GRUPOEXP = 'MAM') then TipoActo = 4;
 ELSE if (GRUPOEXP = 'ECO') then TipoActo = 5;
 ELSE if (GRUPOEXP = 'RM ') then TipoActo = 6;
 */
 /*
 Primer paso: con el tipo de exploracion averiguo el  grupo (de hecho ya me lo pasan) oid como TIPOACTO y cod_grup
 y averiguo los aparatos preferentes y los comentarios para comparar con el horario del tipo de exploracion 
 */

SELECT FIRST 1 TRIM(G.COD_GRUP),TRIM(A.FIL),G.OID,
A.APARATO1,A.APARATO2,A.APARATO3,A.APARATO4,A.APARATO5,A.APARATO6,A.C0MEN1,A.COMEN2,A.COMEN3 
  FROM APARATOS A
  JOIN GAPARATOS G ON G.OID=A.OWNER
  WHERE A.OID=:OID_TIPOEXPLO
INTO :GRUPOEXP,:EXPLO,:TIPOACTO,
:APA1,:APA2,:APA3,:APA4,:APA5,:APA6,:COM1,:COM2,:COM3;
 
      C1=TRIM(COM1);
     C2=TRIM(COM2);
     C3=TRIM(COM3);
 
 FECHABUCLE=:FECHAINI;  
 FECHAFINAL=:FECHAFIN;  


  /*  OBSOLETO, PARA EL CASO QUE USEN MUTUAS LABORALES CON RESERVA DE HORA EN HORARIO 
  AVERIGUAMOS EL CODMUT DE LA MUTUA QUE ENVIAN,*/ 
--  if (MUTUA<1) then begin
--    CODMUTUA=''; 
--  end else begin
    --SELECT M.CODMUT,M.LABORAL FROM MUTUAS M WHERE M.OID=:OID_MUTUA 
    --INTO :CODMUTUA,:LABORAL; 
--end  laboral no se va a tener en cuenta para tuotempo
     --IF ((LABORAL<>'T') OR (LABORAL IS NULL)) THEN CODMUTUA=''; 



 
/*CREAR TABLA TEMPorAL HORAS DEPendIENTE DE LA CONEXION */
/* LA TABLA SIEMPRE EXISTE, LO QUE ES TEMPORAL PARA EL USUARIO SON LAS ROWS 
UNA VEZ CREADA LA TABLA NO SE PUEDE NI BORRAR YA QUE EXISTE DEPENDENCIA DE ESTA MISMA PROCEDURE */
/*  SELECT RDB$RELATION_NAME FROM RDB$RELATIONS
    WHERE RDB$RELATION_NAME = 'HORAS'
    INTO :NombreTabla;
*/
/*AHORA VACIAR LA TABLA AUNQUE AL ACABAR LA TRANSACCION SIEMPRE SE VACIA, PERO SI USAS FLAMEROBIN
 Y EJECUTAS VARIAS VECES SIN COMMIT LA TABLA SE VA RELLENANDO*/ 
 
  DELETE FROM HHORAS_TT;


/* BUSCAMOS CUANTOS APARATOS DEL GRUPO Y CENTRO DADOS ESTAN EN LOS APARATOS 
DEFINIDOS DENTRO DE CADA TIPOAPARATO
*/


        X=0;
        FOR SELECT D.OID,D.COD_FIL
        FROM DAPARATOS D
        WHERE  D.CID=:OID_CENTRO AND D.OWNER=:OID_GRUPO AND D.IOR_EMPRESA=4 AND
          ((D.COD_FIL=:APA1) OR (D.COD_FIL=:APA2) OR (D.COD_FIL=:APA3) OR (D.COD_FIL=:APA4) OR (D.COD_FIL=:APA5) OR (D.COD_FIL=:APA6)) 
        INTO :OID_APA,:FIL_APA
        DO BEGIN
          X=X+1;
          IF (X=1) THEN BEGIN
              OID_APA1=:OID_APA;
              FIL_APA1=:FIL_APA;
          END ELSE IF (X=2) THEN BEGIN
              OID_APA2=:OID_APA;
              FIL_APA2=:FIL_APA;
          END ELSE IF (X=3) THEN BEGIN
              OID_APA3=:OID_APA;
              FIL_APA3=:FIL_APA;  
          END ELSE IF (X=4) THEN BEGIN
              OID_APA4=:OID_APA;
              FIL_APA4=:FIL_APA;   
          END
       END
        
        TVUELTAS=X;
        --SI NO HAY NINGÚN APARATO ENTONCES BUSCAMOS EL PRIMERO DE CENTRO/GRUPO
           IF (X=0) THEN BEGIN
              FOR SELECT FIRST 1 D.OID,D.COD_FIL
              FROM DAPARATOS D
              WHERE  D.CID=:OID_CENTRO AND D.OWNER=:OID_GRUPO AND D.IOR_EMPRESA=4
              INTO :OID_APA,:FIL_APA
              DO BEGIN
                OID_APA1=:OID_APA;
                FIL_APA1=:FIL_APA;
                TVUELTAS=1;
              END
           END       
        
        


/* iniciamos bucle incrementando dia y vuelta hasta conseguir las 1000 horas
daremos una vuelta para cada aparato durente un dia y luego pasaremos al siguiente dia */
 VUELTA=0; 
 HAYHORAS='T';
 
 WHILE (((SELECT COUNT(*) FROM HHORAS_TT)<:NUMERO_HUECOS) ) DO BEGIN 

   VUELTA=VUELTA+1;  -- a cada vuelta añado un aparato de los definidos en la explo 
   
   IF (VUELTA>=TVUELTAS+1) THEN BEGIN 
    --si acaba el bucle  DE aparatos definidos en  la exploracion reinicio vuelta y añado un dia
     VUELTA=1;  
     FECHABUCLE=FECHABUCLE+1;
  END
   
   if (FECHABUCLE > FECHAFINAL) then LEAVE;

   DIASEMANA=(EXTRACT(WEEKDAY FROM :FECHABUCLE)+1);

   
   --si están definidos APA1 o más seguiremos las preferencias
    --CODHORARIO ES EL CODIGO DE APARATO COMPLEJO QUE INCLUYE EL CÓDIGO DE APARATO  O EL CODAPARATO DIRECTAMENTE
    --HORARIO ES EL OID DEL APARATO COMPLEJO QUE INCLUYE EL APARATO O DIRECTAMENTE EL APARATO
    --APARATO  ES EL OID DEL APARATO REAL 
    --CODAPARATO ES EL CODIGO ALFANUMÉRICO

    HORARIO=0;CODHORARIO='';APARATO=0;CODAPARATO='';      
   --si están marcadas las preferncias de aparatos    
      -- primero buscamos si está dentro de aparatos complejos para asigna CODHORARIO

     IF (VUELTA=1) THEN BEGIN 
       CODAPARATO=FIL_APA1;
       APARATO=:OID_APA1;
     END ELSE IF (VUELTA=2) THEN BEGIN
       CODAPARATO=:FIL_APA2;
       APARATO=:OID_APA2;
     END ELSE IF  (VUELTA=3) THEN BEGIN
       CODAPARATO=FIL_APA3;
       APARATO=:OID_APA3;
     END ELSE IF (VUELTA=4) THEN BEGIN 
       CODAPARATO=FIL_APA4;
       APARATO=:OID_APA4;
    END
    HORARIO=:APARATO;
    CODHORARIO=:CODAPARATO;
    
       
       
            SELECT FIRST 1 A.OID,A.APARATO1
            FROM APARATOS_COMPLEJOS A 
            WHERE A.TUOTEMPO='T' AND 
            ( (POSITION(:CODAPARATO IN A.APARATO2)>0) OR (POSITION(:CODAPARATO IN A.APARATO3)>0)
            OR (POSITION(:CODAPARATO IN A.APARATO4)>0) OR (POSITION(:CODAPARATO IN A.APARATO5)>0) 
            OR (POSITION(:CODAPARATO IN A.APARATO6)>0) OR  (POSITION(:CODAPARATO IN A.APARATO7)>0) )
            INTO :HORARIO,:CODHORARIO;  

         
   /* if (CLAUSTRO='T') then begin
       if ((APA1='RM1' or APA2='RM1' or APA3='RM1' or APA4='RM1' or APA5='RM1' or APA6='RM1') 
            and (CENTRO='CDPI')) then begin
        Aparato=60;CodAparato='RM1';APARATO=60;
        IF (VUELTA=2) THEN
        LEAVE;--SI DA MAS VOLTIOS RECARGA DE NUEVO LAS HORAS DE RM1
       end else begin 
        Aparato=0;LEAVE;
       end 
    end */
      
     --como el aparato es específico de centro no hace falta que el centro entre en la ecuación
      --IF (HAYHORAS='T') THEN BEGIN
        SELECT FIRST 1 festivo from festivos where ior_daparatos in (:Aparato,-1) 
        and festivo=:FECHABUCLE
        INTO :DIAFESTIVO;
        IF (DIAFESTIVO=FECHABUCLE) THEN BEGIN
            HAYHORAS='F'; /*NO DEBE SALIR, SOLO SUBIR AL WHILE  */
        END
    --END
   

  IF (HAYHORAS='T') THEN BEGIN /* LOOP*/
  
   SELECT FIRST 1 P.CANTIDAD
   FROM PRECIOS P
   WHERE P.IOR_ENTIDADPAGADORA=:OID_MUTUA AND P.IOR_TIPOEXPLORACION=:OID_TIPOEXPLO
   INTO :CANTIDAD;

   /* BUSCAMOS Por FIN LAS HORAS DEL HORARIO ELEGIDO DE UN SOLO DIA */
   FOR SELECT h.HORA, h.TEXTODEFECTO  
     from HORAS_HORARIO h
   WHERE H.NDIA=:DIASEMANA and  h.IOR_FECHAHORARIO=
      (select FIRST 1 F.OID from FECHA_HORARIO F
      JOIN DAPA_HORARIO D ON (D.OID=F.IOR_HORARIO)
      WHERE D.IOR_APARATO=:HORARIO
      and (F.FINICIO <=:FECHABUCLE)
      and (F.FFIN >=:FECHABUCLE)
   ORDER BY F.TIPO DESC,F.FFIN,F.FINICIO DESC)
   INTO :hHORA, :hTEXTODEFECTO
   DO BEGIN
       INSERT INTO HHORAS_TT (AVAILABILITY_LID,FECHA,HORA,START_TIME,END_TIME,LOCATION_LID,
                                        RESOURCE_LID,ACTIVITY_LID,INSURANCE_LID,CCANTIDAD,APARATO,TEXTODEFECTO,HORARIO_APARATO)
       VALUES (EXTRACT(YEAR FROM :FECHABUCLE)||LPAD(EXTRACT(MONTH FROM :FECHABUCLE),2,0)||LPAD(EXTRACT(DAY FROM :FECHABUCLE),2,0)||SUBSTRING(:HHORA FROM 1 FOR 2)||SUBSTRING(:HHORA FROM 4 FOR 2) ||'_'||:HORARIO||'_'||:APARATO,
       :FECHABUCLE,:HHORA,:HHORA,:HHORA,:OID_CENTRO,:OID_GRUPO,:OID_TIPOEXPLO,:OID_MUTUA,:CANTIDAD,:APARATO,:HTEXTODEFECTO,:CODHORARIO||'_'||:CODAPARATO);
   END
   
  
    --se borran horas anteriores a la hora mínima o máxima
   DELETE FROM HHORAS_TT H WHERE (H.HORA<:HORAMIN) OR (H.HORA>:HORAMAX);
   
   --buscamos las horas con texto cambiado en HORASANULADAS, igual es innecesario cambiar el TEXTO
   FOR  SELECT A.HORA,A.COMENTARIO from HORASANULADAS A
     WHERE (A.FECHA=:FECHABUCLE) and (A.IOR_APARATO=:HORARIO) 
     and (SUBSTRING(A.COMENTARIO FROM 1 FOR 1)<>'>')
   ORDER BY A.HORA
   INTO :HORACAMBIADA,:HTEXTODEFECTO   
   DO BEGIN
      UPDATE HHORAS_TT h SET h.TEXTODEFECTO=:HTEXTODEFECTO 
      WHERE h.HORA=:HORACAMBIADA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO;
   END 

   
   --borramos horas con cero o de mutuas 
   FOR SELECT HORA, TEXTODEFECTO 
   FROM HHORAS_TT
   WHERE FECHA=:FECHABUCLE AND APARATO=:APARATO 
   INTO :HHORA, :HTEXTODEFECTO
   DO BEGIN
      -- si es hoy quitamos las horas anteriores a la hora actual 
      IF ((FECHABUCLE='TODAY') and 
        (:HHORA<(EXTRACT(HOUR FROM CURRENT_TIMESTAMP(0)))||':'||EXTRACT(MINUTE FROM CURRENT_TIMESTAMP(0)))) THEN BEGIN
          DELETE FROM HHORAS_TT h WHERE (h.HORA=:HHORA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO);
      END
      IF (SUBSTRING(:HTEXTODEFECTO FROM 1 For 1)='0') THEN BEGIN 
          --con 0 nunca puede asignarse    
          DELETE FROM HHORAS_TT h WHERE (h.HORA=:HHORA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO);
      
      --end else if ((CODMUTUA<>'') and (POSITION(CODMUTUA IN :HTEXTODEFECTO)=0)) then begin 
         --pasan mutua y comprobamos si está escrito el código en el texto de la hora
          --DELETE FROM HORAS h WHERE (h.HORA=:HHORA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO);

      --end else if ((CODMUTUA='') AND (POSITION(':' in :HTEXTODEFECTO)>0)) then begin 
         --no han pasado mutua por tanto debo quitar todas las horas reservadas a MUTUAS
         -- DELETE FROM HORAS h WHERE (h.HORA=:HHORA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO);

      END ELSE BEGIN
       --if ((COLOPERADA='T') and (EXPLO in ('CC','CL','CD'))) then begin 
         IF (POSITION('*' IN :HTEXTODEFECTO)>0) THEN BEGIN  --con * cuela todo 
            A=A;
         END ELSE IF ((TRIM(C1)='') AND (TRIM(C2)='') AND (TRIM(C3)='')) THEN BEGIN --si no hay condiciones en tipoexploracion NO COMPARAMOS NADA
            A=A;        
        END ELSE IF ((C1 IS NULL) AND (C2 IS NULL) AND(C3 IS NULL)) THEN BEGIN  --LO MISMO, pero solo va con NULL
          A=A;
         END ELSE BEGIN
             IF (:TIPOACTO=12) THEN BEGIN -- PARA TAC COGEMOS CADENAS LARGAS
                A=TRIM(:HTEXTODEFECTO);
                IF ((POSITION(A IN C1)>0) OR (POSITION(A IN C2)>0) OR (POSITION(A IN C3)>0)) 
                   THEN A=A;
                   ELSE DELETE FROM HHORAS_TT H WHERE (H.HORA=:HHORA AND H.FECHA=:FECHABUCLE AND H.APARATO=:APARATO);
            END ELSE BEGIN ----- RESTO  SOLO VALORO LA PRIMERA LETRA    
                A=SUBSTRING(:HTEXTODEFECTO FROM 1 FOR 1);
                IF ((POSITION(A IN C1)>0) OR (POSITION(A IN C2)>0) OR (POSITION(A IN C3)>0))
                    THEN A=A; 
                    ELSE DELETE FROM HHORAS_TT h WHERE (h.HORA=:HHORA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO);   
            END
         END
      END 
   END --FOR SELECT FROM HORAS DO BEGIN 

   FOR SELECT A.HORA from HORASANULADAS A
     WHERE (A.FECHA=:FECHABUCLE) and (A.IOR_APARATO=:HORARIO) 
        AND (SUBSTRING(A.COMENTARIO FROM 1 FOR 1)='>')
        ORDER BY A.HORA
   INTO :HORAANULADA   
   DO BEGIN
      DELETE FROM HHORAS_TT h WHERE h.HORA=:HORAANULADA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO;
   END 
   
   FOR SELECT E.HORA FROM EXPLORACION E
     WHERE E.FECHA=:FECHABUCLE and E.IOR_APARATO=:APARATO  and (E.ESTADO<>'1')
     ORDER BY e.HORA
   INTO :HORAOCUPADA
   DO BEGIN
        DELETE FROM HHORAS_TT h WHERE h.HORA=:HORAOCUPADA AND h.FECHA=:FECHABUCLE AND h.APARATO=:APARATO;
   END
  END /*final del HAYHORAS=FALSE*/
END /*final del while */
  
   FOR SELECT  H.AVAILABILITY_LID,H.FECHA,H.HORA,H.START_TIME,H.END_TIME,H.LOCATION_LID, H.RESOURCE_LID,H.ACTIVITY_LID,
   H.INSURANCE_LID,H.CCANTIDAD,H.TEXTODEFECTO,H.HORARIO_APARATO
   FROM HHORAS_TT H ORDER BY  H.FECHA,H.HORA   
    INTO :AVAILABILITY_LID,:FECHA,:HORA,:START_TIME,:END_TIME,:LOCATION_LID, :RESOURCE_LID,:ACTIVITY_LID,
   :INSURANCE_LID,:CCANTIDAD,:TEXTODEFECTO,:HORARIO_APARATO

  DO BEGIN

    H2HORA=DATEADD(15 MINUTE TO CAST('01-01-2000'||' '||:HORA AS TIMESTAMP));
    H3HORA=EXTRACT(HOUR FROM CAST(H2HORA AS TIMESTAMP));
    H3HORA=LPAD(H3HORA,2,0)||':'||LPAD(EXTRACT(MINUTE FROM CAST(H2HORA AS TIMESTAMP)),2,0);


      AVAILABILITY_LID=:AVAILABILITY_LID;
      FECHA=:FECHA;
      START_TIME=:HORA;
      END_TIME=:H3HORA;
      LOCATION_LID=:LOCATION_LID; --OID DEL CENTRO 
      RESOURCE_LID=:RESOURCE_LID;  --GRUPO EXPLORACION
      ACTIVITY_LID=:ACTIVITY_LID;  -- OID TIPOEXPLORACION
      INSURANCE_LID=:INSURANCE_LID;  --OID MUTUA
      CCANTIDAD=:CCANTIDAD;
      TEXTODEFECTO=:TEXTODEFECTO;
      HORARIO_APARATO=:HORARIO_APARATO;
      SUSPEND;    
 
  END  
end^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE HUECOSLIBRES_TUOTEMPO TO  SYSDBA;

