CREATE GLOBAL TEMPORARY TABLE HHORAS_TT
(
  AVAILABILITY_LID VARCHAR(30),
  FECHA TIMESTAMP,
  HORA VARCHAR(5),
  START_TIME VARCHAR(5),
  END_TIME VARCHAR(5),
  LOCATION_LID INTEGER,
  RESOURCE_LID INTEGER,
  ACTIVITY_LID INTEGER,
  INSURANCE_LID INTEGER,
  CCANTIDAD NUMERIC(8,2),
  TEXTODEFECTO VARCHAR(50),
  APARATO INTEGER,
  HORARIO_APARATO VARCHAR(20)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON HHORAS_TT TO  SYSDBA WITH GRANT OPTION;

