SET TERM ^ ;
ALTER PROCEDURE FACTURACION_EVOLUTIVA (
    FECHAINICIAL TIMESTAMP,
    FECHAFINAL TIMESTAMP,
    MUTUA VARCHAR(100),
    CENTRO INTEGER,
    PAGADO VARCHAR(1),
    GPR INTEGER,
    COLEGIADO INTEGER,
    MEDICO INTEGER,
    FACTURADO VARCHAR(1) )
RETURNS (
    ORDEN INTEGER,
    ANUAL INTEGER,
    COD_GRUP VARCHAR(10),
    SEXPLO NUMERIC(9,2),
    PEXPLO NUMERIC(9,2),
    SCONSUM NUMERIC(9,2),
    STOTAL NUMERIC(9,2),
    CEXPLO INTEGER )
AS
DECLARE MES INTEGER;
  DECLARE VARIABLE pCENTROMAX INTEGER;
  DECLARE VARIABLE pCENTROMIN INTEGER;
  DECLARE VARIABLE pMUTUAMAX INTEGER;
  DECLARE VARIABLE pMUTUAMIN INTEGER;
  DECLARE VARIABLE pPAGADO VARCHAR(1);
  DECLARE VARIABLE pFACTURADO VARCHAR(1);
  DECLARE VARIABLE pGPRMIN INTEGER; 
  DECLARE VARIABLE pGPRMAX INTEGER;
  DECLARE VARIABLE pCOLEGIADOMAX INTEGER;
  DECLARE VARIABLE pCOLEGIADOMIN INTEGER;
  DECLARE VARIABLE pMEDICOMAX INTEGER;
  DECLARE VARIABLE pMEDICOMIN INTEGER;
  DECLARE VARIABLE MUTUA0 INTEGER;
  DECLARE VARIABLE MUTUA1 INTEGER;
  DECLARE VARIABLE MUTUA2 INTEGER;
  DECLARE VARIABLE MUTUA3 INTEGER;
  DECLARE VARIABLE MUTUA4 INTEGER;
  DECLARE VARIABLE MUTUA5 INTEGER;
  DECLARE VARIABLE MUTUA6 INTEGER;
  DECLARE VARIABLE MUTUA7 INTEGER;
  DECLARE VARIABLE MUTUA8 INTEGER;
  DECLARE VARIABLE MUTUA9 INTEGER;
  
BEGIN
 MUTUA0=0;MUTUA1=0;MUTUA2=0;MUTUA3=0;MUTUA4=0;MUTUA5=0;MUTUA6=0;MUTUA7=0;MUTUA8=0;MUTUA9=0;
 MUTUA=SUBSTRING(MUTUA FROM 2 FOR (CHAR_LENGTH(MUTUA)-2));
 IF (MUTUA='0,') then begin 
   pMUTUAMAX=1000000000;pMUTUAMIN=0; 
 end else begin 
   pMUTUAMAX=0;pMUTUAMIN=0;
   MUTUA0=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   --pMUTUAMAX=MUTUA0;pMUTUAMIN=MUTUA0; 
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA1=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA2=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA3=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA5=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA5=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA6=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA7=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA8=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
   MUTUA=SUBSTRING(MUTUA FROM (POSITION(',' IN MUTUA)+1) FOR 100);
   IF (CHAR_LENGTH(MUTUA)>2) then begin 
     MUTUA9=CAST(SUBSTRING(MUTUA FROM 1 FOR (POSITION(',',MUTUA,1)-1)) AS INTEGER);
   end
 end
  
 /*IF (MUTUA>0) then begin 
   pMUTUAMAX=:MUTUA;pMUTUAMIN=:MUTUA;
 end else begin 
   pMUTUAMAX=1000000000;pMUTUAMIN=0;
 end */ 
 
 IF (CENTRO>0) then begin 
   pCENTROMAX=:CENTRO;pCENTROMIN=:CENTRO;
 end else begin 
   pCENTROMAX=1000000000;pCENTROMIN=0;
 end
 
  IF (GPR>0) then begin 
   pGPRMAX=:GPR;pGPRMIN=:GPR;
 end else begin 
   pGPRMAX=3;pGPRMIN=0;
 end 
 
 IF (PAGADO IN ('T','F')) then begin 
   pPAGADO=:PAGADO;
 end else begin 
   pPagado='%';
 end
 
 IF (COLEGIADO>0) then begin
   pCOLEGIADOMIN=:COLEGIADO;pCOLEGIADOMAX=:COLEGIADO;
 end else begin
   pCOLEGIADOMIN=-1;pCOLEGIADOMAX=1000000000;
 end

 IF (MEDICO>0) then begin
   pMEDICOMIN=:MEDICO;pMEDICOMAX=:MEDICO;
 end else begin
   pMEDICOMIN=-1;pMEDICOMAX=1000000000;
 end
 
 IF (FACTURADO IN ('T','F')) then begin 
   pFACTURADO=:FACTURADO;
 end else begin 
   pFACTURADO='%';
 end
 
 
 DELETE FROM HFACTURACIONMENSUAL;
     
 for select 1 AS ORDEN, EXTRACT(YEAR FROM E.FECHA) as ANUAL,G.COD_GRUP,
        SUM(e.cantidad) as SEXPLO,
        AVG(E.CANTIDAD) AS PEXPLO,
        COUNT(E.OID) AS CEXPLO
    from EXPLORACION e 
    JOIN GAPARATOS G ON G.OID = E.IOR_GRUPO
    where e.ESTADO = '3'  and (NOT e.IOR_GRUPO IN (10,18)) and 
    (E.FECHA between :FECHAINICIAL and  :FECHAFINAL) 
    and (e.IOR_MEDICO BETWEEN :pMEDICOMIN and :pMEDICOMAX) and (E.IOR_COLEGIADO BETWEEN :pCOLEGIADOMIN and :pCOLEGIADOMAX) 
    and (e.OWNER BETWEEN :pCentroMin and :pCentroMax) 
    and ((e.IOR_ENTIDADPAGADORA BETWEEN :pMutuaMin and :pMutuaMax)
           OR e.IOR_ENTIDADPAGADORA IN (:MUTUA0,:MUTUA1,:MUTUA2,:MUTUA3,:MUTUA4,:MUTUA5,:MUTUA6,:MUTUA7,:MUTUA8,:MUTUA9))
    and (e.IOR_GPR BETWEEN :pGPRMin and :pGPRMax) and (e.PAGADO LIKE '%'||:pPagado) and (e.FACTURADA LIKE '%'||:pFACTURADO)
    group by EXTRACT(YEAR FROM E.FECHA), G.COD_GRUP
    --PLAN JOIN (SORT (JOIN ( E INDEX (IDXEXPLORACIONFECHA,IDXEXPLORACIONCOLEGIADO,IDXEXPLORACIONMEDICO, IDXEXPLORACIONMUTUAS), 
    --                    G INDEX (GAPARATOSPRIMARYKEY1))))
  
    UNION
    
    select 2 AS ORDEN, EXTRACT(YEAR FROM E.FECHA) as ANUAL, 'TOTAL' AS COD_GRUP,
        SUM(e.cantidad) as SEXPLO, 
        AVG(E.CANTIDAD) AS PEXPLO,
        count(E.OID) as CEXPLO

    from EXPLORACION e
    where e.ESTADO = '3'  and (NOT e.IOR_GRUPO IN (10,18)) and 
    (E.FECHA between :FECHAINICIAL and  :FECHAFINAL) 
    and (e.OWNER BETWEEN :pCentroMin and :pCentroMax) 
    and ((e.IOR_ENTIDADPAGADORA BETWEEN :pMutuaMin and :pMutuaMax)
      OR e.IOR_ENTIDADPAGADORA IN (:MUTUA0,:MUTUA1,:MUTUA2,:MUTUA3,:MUTUA4,:MUTUA5,:MUTUA6,:MUTUA7,:MUTUA8,:MUTUA9))       
    and (E.IOR_COLEGIADO BETWEEN :pCOLEGIADOMIN and :pCOLEGIADOMAX) and (e.IOR_MEDICO BETWEEN :pMEDICOMIN and :pMEDICOMAX)
    and (e.IOR_GPR BETWEEN :pGPRMin and :pGPRMax) and (e.PAGADO LIKE '%'||:pPagado) and (e.FACTURADA LIKE '%'||:pFACTURADO)
    group by EXTRACT(YEAR FROM E.FECHA),COD_GRUP 
    --PLAN JOIN (SORT (JOIN ( E INDEX (IDXEXPLORACIONFECHA,IDXEXPLORACIONCOLEGIADO,IDXEXPLORACIONMEDICO, IDXEXPLORACIONMUTUAS))))  
 

  INTO :ORDEN,:ANUAL,:COD_GRUP,:SEXPLO,:PEXPLO,:CEXPLO
 --pongo MES para el campo ANUAL
  do begin
    INSERT INTO HFACTURACIONMENSUAL (ORDEN,MES,COD_GRUP,SACTUAL,PACTUAL,CACTUAL)
       VALUES (:ORDEN,:ANUAL,:COD_GRUP,:SEXPLO,:PEXPLO,:CEXPLO);   
  end


  FOR SELECT EXTRACT(YEAR FROM E.FECHA) as ANUAL,G.COD_GRUP,SUM(x.PRECIO) as sCONSUM
              
    --from EXP_CONSUM X
    --JOIN EXPLORACION E ON E.OID=X.IOR_EXPLORACION 
    from EXPLORACION e
    join EXP_CONSUM x on x.IOR_EXPLORACION=e.OID
    JOIN GAPARATOS G ON G.OID = E.IOR_GRUPO
    where e.ESTADO = '3'  and (NOT e.IOR_GRUPO IN (10,18)) and 
    (E.FECHA between :FECHAINICIAL and  :FECHAFINAL) 
    and (e.OWNER BETWEEN :pCentroMin and :pCentroMax) 
    and ((e.IOR_ENTIDADPAGADORA BETWEEN :pMutuaMin and :pMutuaMax)
         OR e.IOR_ENTIDADPAGADORA IN (:MUTUA0,:MUTUA1,:MUTUA2,:MUTUA3,:MUTUA4,:MUTUA5,:MUTUA6,:MUTUA7,:MUTUA8,:MUTUA9))
    and (e.IOR_GPR BETWEEN :pGPRMin and :pGPRMax) and (e.PAGADO LIKE '%'||:pPagado) and (e.FACTURADA LIKE '%'||:pFACTURADO)
    and (E.IOR_COLEGIADO BETWEEN :pCOLEGIADOMIN and :pCOLEGIADOMAX) and (e.IOR_MEDICO BETWEEN :pMEDICOMIN and :pMEDICOMAX)
    group by EXTRACT(YEAR FROM E.FECHA),G.COD_GRUP
    --PLAN SORT ((E INDEX (IDXEXPLORACIONFECHA,IDXEXPLORACIONMEDICO,IDXEXPLORACIONCOLEGIADO, IDXEXPLORACIONMUTUAS)),
    --    G INDEX (GAPARATOSPRIMARYKEY1), X INDEX (IDXEXP_CONSUMEXP))
    
    UNION
    
    SELECT EXTRACT(YEAR FROM E.FECHA) as ANUAL,'TOTAL' AS COD_GRUP, SUM(x.PRECIO) as sCONSUM
 
    --from EXP_CONSUM X
    --JOIN EXPLORACION E ON E.OID=X.IOR_EXPLORACION 
    from EXPLORACION e
    join EXP_CONSUM x on x.IOR_EXPLORACION=e.OID
    where e.ESTADO = '3'  and (NOT e.IOR_GRUPO IN (10,18)) and 
    (E.FECHA between :FECHAINICIAL and  :FECHAFINAL) 
    and (e.OWNER BETWEEN :pCentroMin and :pCentroMax) 
    and ((e.IOR_ENTIDADPAGADORA BETWEEN :pMutuaMin and :pMutuaMax)
         OR e.IOR_ENTIDADPAGADORA IN (:MUTUA0,:MUTUA1,:MUTUA2,:MUTUA3,:MUTUA4,:MUTUA5,:MUTUA6,:MUTUA7,:MUTUA8,:MUTUA9))
    and (e.IOR_GPR BETWEEN :pGPRMin and :pGPRMax) and (e.PAGADO LIKE '%'||:pPagado) and (e.FACTURADA LIKE '%'||:pFACTURADO)
    and (E.IOR_COLEGIADO BETWEEN :pCOLEGIADOMIN and :pCOLEGIADOMAX) and (e.IOR_MEDICO BETWEEN :pMEDICOMIN and :pMEDICOMAX)
    group by EXTRACT(YEAR FROM E.FECHA),COD_GRUP
    --PLAN SORT ((E INDEX (IDXEXPLORACIONFECHA,IDXEXPLORACIONMEDICO,IDXEXPLORACIONCOLEGIADO, IDXEXPLORACIONMUTUAS)),
    --    X INDEX (IDXEXP_CONSUMEXP))

  INTO :ANUAL,:COD_GRUP,:sCONSUM
  do begin 
    UPDATE HFACTURACIONMENSUAL SET SACTUALCONSUM=:SCONSUM
        WHERE MES=:ANUAL AND COD_GRUP=:COD_GRUP ;
  end

  FOR SELECT ORDEN,MES, COD_GRUP,SACTUAL,PACTUAL,SACTUALCONSUM,(SACTUAL+COALESCE(SACTUALCONSUM,0)) AS SACTUALTOTAL,CACTUAL
    FROM HFACTURACIONMENSUAL
    ORDER BY 2,1,3
    INTO :ORDEN,:MES,:COD_GRUP,:SEXPLO,:PEXPLO,:SCONSUM,:STOTAL,:CEXPLO


DO BEGIN
  ORDEN=:ORDEN;
  ANUAL=:MES;
  COD_GRUP=:COD_GRUP;
  SEXPLO=:SEXPLO;
  PEXPLO=:PEXPLO;
  SCONSUM=:SCONSUM;
  STOTAL=:STOTAL;
  CEXPLO=:CEXPLO;
  SUSPEND;
END
END
^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE FACTURACION_EVOLUTIVA TO  AFFIDEA;

GRANT EXECUTE
 ON PROCEDURE FACTURACION_EVOLUTIVA TO  SYSDBA;

