CREATE TABLE CE_MUTUAS
(
  OID INTEGER,
  VERS INTEGER,
  CID INTEGER,
  CANAL VARCHAR(6),
  OWNER INTEGER,
  USERNAME VARCHAR(20),
  MODIF TIMESTAMP,
  BORRADO VARCHAR(1),
 IOR_CENTROEXTERNO INTEGER,
 IOR_MUTUA INTEGER,
  CONSTRAINT PK_CE_MUTUAS PRIMARY KEY (OID)
);

COMMIT;

CREATE INDEX IDXCE_MUTUAS_CE ON CE_MUTUAS(IOR_CENTROEXTERNO);
CREATE INDEX IDXCE_MUTUAS_MUTUAS ON CE_MUTUAS(IOR_MUTUA);

COMMIT;
GRANT SELECT
 ON CE_MUTUAS TO  AFFIDEA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CE_MUTUAS TO  SYSDBA WITH GRANT OPTION;

COMMIT;


CREATE TABLE CE_MEDICOS
(
  OID INTEGER,
  VERS INTEGER,
  CID INTEGER,
  CANAL VARCHAR(6),
  OWNER INTEGER,
  USERNAME VARCHAR(20),
  MODIF TIMESTAMP,
  BORRADO VARCHAR(1),
 IOR_CENTROEXTERNO INTEGER,
 IOR_MEDICO INTEGER,
  CONSTRAINT PK_CE_MEDICOS PRIMARY KEY (OID)
);

COMMIT;

CREATE INDEX IDXCE_MEDICOS_CE ON CE_MEDICOS (IOR_CENTROEXTERNO);
CREATE INDEX IDXCE_MEDICOS_MEDICOS ON CE_MEDICOS(IOR_MEDICO);

COMMIT;
GRANT SELECT
 ON CE_MEDICOS TO  AFFIDEA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CE_MEDICOS TO  SYSDBA WITH GRANT OPTION;

COMMIT;