ALTER TABLE UCCADUSER 
ADD FECHA_CADUCIDAD TIMESTAMP,
ADD INTENTOS_FALLIDOS INTEGER,
ADD BLOQUEO_USUARIO VARCHAR(1);
COMMIT;
UPDATE UCCADUSER 
SET FECHA_CADUCIDAD=CURRENT_DATE,
BLOQUEO_USUARIO='F',
INTENTOS_FALLIDOS = 0;
COMMIT;
