INSERT INTO WEBCONFIG
(OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION)
VALUES(gen_id(GENUID,1),1, NULL, 'RutaWLAffidea', 'c:\RADIOIB\RADIO\RADIOIBD7\WORKLIST\AFFIDEA', 'RUTAS', NULL);

INSERT INTO WEBCONFIG
(OID, VERS, OWNER, CLAVE, VALOR, SECCION, DESCRIPCION)
VALUES(gen_id(GENUID,1),0, NULL, 'RutaWLAffidea', '\\SRVSECWEB\Affidea\worklist', 'RUTAS', NULL);