//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAMULTIPLE
    {
        public int ID { get; set; }
        public string DIASEMANA { get; set; }
        public string  FECHA{ get; set; }
        public DAPARATOS APARATO {get; set; }        
        public string TEXTO { get; set; }
        
    }
}
