//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using RadioWeb.Models.Repos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RadioWeb.Models
{

    [Table("APARATOS_COMPLEJOS")]
    public partial class AparatosComplejos
    {
        public AparatosComplejos()
        {

            this.DAPARATOS = DaparatoRepositorio.ListaV2();

        }

        [Key]
        public int OID { get; set; }
        public string BORRADO { get; set; }
        public string APARATO1 { get; set; }
        public string APARATO2 { get; set; }
        public string APARATO3 { get; set; }
        public string APARATO4 { get; set; }
        public string APARATO5 { get; set; }
        public string APARATO6 { get; set; }
        public string APARATO7 { get; set; }
        public string APARATO8 { get; set; }
        public string APARATO9 { get; set; }    
        [NotMapped]
        public List<DAPARATOS> DAPARATOS { get; set; }

        [NotMapped]
        public string ACTION
        {
            get
            {
                return (OID > 0) ? "Update" : "Create";
            }

        }

    }
}