//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class APARATOS
    {
        [Key]
        public int OID { get; set; }

        [Display(Name = "CLAUSTROFOBIA")]
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public string COD_FIL { get; set; }
        [Display(Name = "DESCRIPCIÓN")]
        public string DES_FIL { get; set; }

        [Display(Name = "EXPLOR.")]
        public string FIL { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string TEXTO { get; set; }
        public Nullable<int> SALIDA_INTERNET { get; set; }
        public string TEXTO_INTERNET { get; set; }
        public string APARATO1 { get; set; }
        public string APARATO2 { get; set; }
        public string APARATO3 { get; set; }
        public string APARATO4 { get; set; }
        public string APARATO5 { get; set; }
        public string APARATO6 { get; set; }
        public string C0MEN1 { get; set; }
        public string COMEN2 { get; set; }
        public string COMEN3 { get; set; }
        public Nullable<int> RECUENTO { get; set; }

        [NotMapped]
        public string SMS { get; set; }
        [NotMapped]
        public double PRECIO { get; set; }
        [NotMapped]
        public virtual EMPRESAS EMPRESA { get; set; }
        [NotMapped]
        public virtual GAPARATOS GRUPOAPARATOS { get; set; }

        public virtual ICollection<PRECIOS> PRECIOS { get; set; }
    }
}
