//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using RadioWeb.Models.Repos;
    using RadioWeb.ViewModels;
    using RadioWeb.ViewModels.Exploracion;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class BOLSA_PRUEBAS
    {
        public BOLSA_PRUEBAS()
        {
            this.IOR_COLEGIADO = -1;
            this.IOR_ENTIDADPAGADORA = -1;
            this.IOR_CENTROEXTERNO = -1;
            this.IOR_GAPARATO = -1;
            this.IOR_TIPOEXPLORACION = -1;
            this.SEXO = "H";
            this.GAPARATO = new List<GAPARATOS>();
            foreach (var item in GAparatoRepositorio.Lista())
            {
                if (item.CID==1)
                {
                    this.GAPARATO.Add(item);
                }
                
            }

        }
        [Key]
        public int OID { get; set; }
        //[NotMapped]
        [DisplayName("SEXO")]
        [DataType("SEXO")]
        [Required]
        public string SEXO { get; set; }

        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public int OWNER { get; set; }
        public string USERNAME { get; set; }
        public string BORRADO { get; set; }
        public DateTime FECHAENTRADA { get; set; }
        public string PACIENTE { get; set; }
        public string TEXTO { get; set; }
        [Required]
        [NotMapped]
        public string NOMBRE { get; set; }

        [Required]
        [NotMapped]
        public string APELLIDOS { get; set; }

        [DisplayName("FECHA NAC.")]
        [DataType("FECHAMASK")]
        [Required]
        public DateTime FECHANACIMIENTO { get; set; }

        [DataType("TIPO_DOC")]
        [Display(Name = "TIPO DOC")]
        public int TIPO_DOC { get; set; }


        [Display(Name = "IDENTIFICACION PERSONAL")]
        public string DNI { get; set; }
        public string POLIZA { get; set; }
        public string PASAPORTE { get; set; }


        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail no válido")]
        public string MAIL { get; set; }

        [Required]
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string DIRECCION { get; set; }
        public string CODIGOPOSTAL { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }


        [Display(Name = "FECHA AGENDADA")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FECHAPRUEBA { get; set; }


        [Display(Name = "FECHA RESULTADO")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FECHARESULTADO { get; set; }


        [Display(Name = "HORA AGENDADA")]
        public string HORAPRUEBA { get; set; }
        public string PRUEBA { get; set; }

        [DataType(DataType.MultilineText)]
        public string COMENTARIO { get; set; }
        public int IOR_COLEGIADO { get; set; }
        public string MEDICOREFERENTE { get; set; }
        public string MUTUA { get; set; }

        [NotMapped]
        public string CENTROEXTERNO { get; set; }


        [DataType("TIPOEXPLORACION")]
        [Display(Name = "PRUEBA")]
        [Range(0, 100000000, ErrorMessage = "Seleccione Exploracion")]
        public int IOR_TIPOEXPLORACION { get; set; }

        public int? IOR_EXPLORACION { get; set; }

        [DataType("GAPARATO")]
        [Display(Name = "TIPO")]
        public int IOR_GAPARATO { get; set; }


        [NotMapped]
        public List<GAPARATOS> GAPARATO { get; set; }



        public string EXPLORACION { get; set; }

        [NotMapped]
        public EXPLORACION EXPLORACIONAGENDADA { get; set; }

        [NotMapped]
        public string PETICIONESANOMBREDEMUTUA { get; set; }


        [NotMapped]
        public string PETICIONESANOMBREDECOLEGIADO { get; set; }

        [NotMapped]
        public string PETICIONESANOMBREDECENTROEXTERNO { get; set; }

        [DataType("PRIORIDAD")]
        public string PRIORIDAD { get; set; }

        [DataType("MUTUASLISTCITAONLINE")]
        [Display(Name = "MUTUA")]
        [Range(-1, 100000000, ErrorMessage = "Seleccione Mutua")]
        public int? IOR_ENTIDADPAGADORA { get; set; }

        [DataType("CENTROEXTERNO")]
        [Display(Name = "CENTRO EXTERNO")]
        public int? IOR_CENTROEXTERNO { get; set; }

        [NotMapped]
        public HttpPostedFileBase DOCUMENTO { get; set; }


        public int? IOR_DOCUMENTO { get; set; }

        [DataType("TIPO_DOC")]
        [Display(Name = "TIPO DOC")]
        public int? IOR_TIPODOC { get; set; }


        [NotMapped]
        public string ACTION
        {
            get
            {
                return (OID != 0) ? "Edit" : "Create";
            }

        }

        [Display(Name = "A PARTIR DE")]
        [NotMapped]
        public string HORAINICIOBUSQUEDA { get; set; }

       
        
        [Display(Name = "CENTRO")]
        [DataType("CENTROS")]
        public int IOR_CENTRO { get; set; }

        public Nullable<int> IOR_MOTDESPROG { get; set; }


    }
}
