//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;



    public class CEMEDICOS
    {
        public int OID { get; set; }
        public int? VERS { get; set; }
        public int? CID { get; set; }
        public string CANAL { get; set; }
        public int? OWNER { get; set; }
        public string USERNAME { get; set; }
        public DateTime? MODIF { get; set; }
        public string BORRADO { get; set; }
        public int? IOR_CENTROEXTERNO { get; set; } // Relación con el centro externo
        public int? IOR_MEDICO { get; set; } // Relación con el médico o colegiado
    }





}
