//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROSEXTERNOS
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public Nullable<double> CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string COD_MUT { get; set; }
        public string COD_CAP { get; set; }
        public string COD_DAP { get; set; }
        public Nullable<short> PREFIJO { get; set; }
        public string NIF { get; set; }
        public string CONTACTO { get; set; }
        public string TRATA { get; set; }
        public string NUM_CLI { get; set; }
        public string CODMUT { get; set; }
        public Nullable<int> IOR_DAP { get; set; }
        public string CONTRATOICS { get; set; }
        public string CODIICS { get; set; }
        public Nullable<int> IOR_CENTRAL { get; set; }
        public string TIPOPAGO { get; set; }
        public string DIASCARENCIA { get; set; }
        public string MAILING { get; set; }
        public INFOMUTUAS INFOMUTUA { get; set; }

        public Nullable<int> IOR_MUTUA { get; set; }

    }
}
