//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class CENTROSEXTERNOS
    {
        public CENTROSEXTERNOS()
        {
            this.DIRECCIONES = new HashSet<DIRECCION>();
            this.TELEFONOS = new HashSet<TELEFONO>();
            this.MutuasRelacionadas = new List<MUTUAS>();
            this.ColegiadosRelacionados = new List<COLEGIADOS>();
        }
        [Key]
        public int OID { get; set; }
        public int? VERS { get; set; }
        public int? CID { get; set; }

        [DataType("BooleanString")]
        [Display(Name = "CITAONLINE")]
        public string CANAL { get; set; }
        public int? OWNER { get; set; }
        public string USERNAME { get; set; }
        public DateTime? MODIF { get; set; }
        public int? IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public double? CODIGO { get; set; }
        public string NOMBRE { get; set; }

        [Display(Name = "Código Centro")]
        public string COD_MUT { get; set; }
        public string COD_CAP { get; set; }
        public string COD_DAP { get; set; }
        public short? PREFIJO { get; set; }
        public string NIF { get; set; }
        public string CONTACTO { get; set; }
        public string TRATA { get; set; }
        public string NUM_CLI { get; set; }
        public string CODMUT { get; set; }
        public int? IOR_DAP { get; set; }
        public string CONTRATOICS { get; set; }
        public string CODIICS { get; set; }
        public int? IOR_CENTRAL { get; set; }
        public string TIPOPAGO { get; set; }
        public string DIASCARENCIA { get; set; }
        public string MAILING { get; set; }

        [Display(Name = "Email")]
        public string MAIL { get; set; }
        public int? IOR_MUTUA { get; set; }

        [UIHint("DIRECCION")]
        public virtual ICollection<DIRECCION> DIRECCIONES { get; set; }

        [UIHint("TELEFONO")]
        public virtual ICollection<TELEFONO> TELEFONOS { get; set; }

      
        [NotMapped]
        public string TEXTO { get; set; }


        
        // Relación con Mutuas
        public virtual List<MUTUAS> MutuasRelacionadas { get; set; }


      
        // Relación con Colegiados
        public virtual List<COLEGIADOS> ColegiadosRelacionados { get; set; }
    }

}
