//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CENTROS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> OWNER { get; set; }
        public short ORDEN { get; set; }
        public string NOMBRE { get; set; }
        public string CANAL { get; set; }
        public byte[] LOGO { get; set; }
        public string BORRADO { get; set; }
        public string HORARIO { get; set; }
        public string HORARIO2 { get; set; }
        public string LOGO_URL { get; set; }
        public int LOGO_HEIGHT { get; set; }
        public int LOGO_WIDTH { get; set; }
        public string DESCRIPCIO { get;  set; }
        public string DIRECCION { get;  set; }

    }
}
