//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_DEF
    {
        public int CID { get; set; }
        public Nullable<int> VERS { get; set; }
        public string CLASS_NAME { get; set; }
        public string TABLE_NAME { get; set; }
    }
}
