//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLEGIADOS
    {

        public COLEGIADOS()
        {
            this.DIRECCIONES = new HashSet<DIRECCION>();
            this.TELEFONOS = new HashSet<TELEFONO>();
        }
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string NOMBRE { get; set; }
        public string TRATA { get; set; }
        public string COD_MED { get; set; }
        public string ESPEC { get; set; }
        public string NIF { get; set; }
        public string MAILING { get; set; }
        public Nullable<double> PRIVADOS { get; set; }
        public Nullable<double> MUTUAS { get; set; }
        public Nullable<double> ICS { get; set; }
        public string HORAMOD { get; set; }
        public string MAILING1 { get; set; }
        public string MAILING2 { get; set; }
        public Nullable<int> IOR_ESPECIALIDAD { get; set; }
        public Nullable<int> IOR_CENTRO { get; set; }
        public Nullable<int> IOR_EXPLORACION{ get; set; }
        public string RIP { get; set; }
        public string TRATAMIENTODESC { get; set; }
        public virtual CENTROSEXTERNOS CENTRO { get; set; }
        public virtual ESPECIALIDADES ESPECIALIDAD { get; set; }
        public string TEXTO { get; set; }
        public string EMAIL { get; set; }
        public virtual ICollection<DIRECCION> DIRECCIONES { get; set; }
        public virtual ICollection<TELEFONO> TELEFONOS { get; set; }

      
    }
}
