//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION
    {
        public int OID { get; set; }
        public Nullable<int> SCREENSAVERTIME { get; set; }
        public string SCREENSAVER { get; set; }
        public Nullable<int> MARGENDCHO { get; set; }
        public Nullable<int> MARGENIZDO { get; set; }
        public Nullable<int> CAPTIONCOLORFROM { get; set; }
        public Nullable<int> CAPTIONCOLORTO { get; set; }
        public Nullable<int> PANELCOLORFROM { get; set; }
        public Nullable<int> PANELCOLORTO { get; set; }
        public Nullable<int> CAPTIONCOLOR { get; set; }
        public Nullable<int> AS_CAPTIONCOLORFROM { get; set; }
        public Nullable<int> AS_CAPTIONCOLORTO { get; set; }
        public Nullable<int> AS_PANELCOLORFROM { get; set; }
        public Nullable<int> AS_PANELCOLORTO { get; set; }
        public Nullable<int> AS_CAPTIONCOLOR { get; set; }
        public string DIRECTORIOIMAGENES { get; set; }
        public string DIRTEMPIMAGENES { get; set; }
    }
}
