//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOSICS
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string CANAL { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string NOMBRE { get; set; }
        public string NIF { get; set; }
        public string CONTACTO { get; set; }
        public string CONTRATOICS { get; set; }
        public string CODIICS { get; set; }
        public string COMENTARIO { get; set; }
    }
}
