//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using RadioWeb.Models.Repos;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DAPARATOS")]
    public partial class DAPARATOS
    {
        public DAPARATOS()
        {
            this.CENTROS = CentrosRepositorio.List();
        }


        [Key]
        public int OID { get; set; }

        [Display(Name = "VISIBLE")]
        public Nullable<int> VERS { get; set; }

        //Virtual CENTROS
        [DataType("CENTRO")]
        [DisplayName("CENTRO")]
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public int OWNER { get; set; }

        [Display(Name = "MODALITY")]
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }

        [Display(Name = "APARATO")]
        public string COD_FIL { get; set; }

        [Display(Name = "DESCRIPCIÓN")]
        public string DES_FIL { get; set; }
        public Nullable<int> TOT_FIL { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }

        [Display(Name = "IDENTIFICADOR WL")]
        public string IDENTIFICADOR { get; set; }
        public Nullable<int> XEROX { get; set; }

        [Display(Name = "DESCRIPCIÓN KIOSKO")]
        public string KIOSKO_DES { get; set; }

        [NotMapped]
        public virtual EMPRESAS EMPRESA { get; set; }
        [NotMapped]
        public virtual GAPARATOS GRUPOAPARATOS { get; set; }
        [NotMapped]
        public virtual CENTROS CENTRO { get; set; }
        [NotMapped]
        public List<CENTROS> CENTROS { get; set; }
        [NotMapped]
        public virtual int SALA { get; set; }


        //Esta propiedad la utilizamos para la Agenda multiple
        //public List<LISTADIAAMBFORATS> oListaDia { get; set; }
    }
}
