//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DIRECCION")]
    public partial class DIRECCION
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public int OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> CENTRO { get; set; }

        [Column("DIRECCION")]
        [DisplayName("Calle")]        
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Calle no válida")]
        public string DIRECCION1 { get; set; }
      
        [DisplayName("CP")]      
        public string CP { get; set; }

        [DisplayName("Población")]
        public string POBLACION { get; set; }

        public string PROVINCIA { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string PAIS { get; set; }
        public string BORRADO { get; set; }
        public string MAILING { get; set; }
        public string MAILING1 { get; set; }
        public string MAILING2 { get; set; }
        public Nullable<int> IOR_TIPO { get; set; }
        [NotMapped]
        public int INDICE { get; set; }


        public virtual MUTUAS MUTUA { get; set; }
        public virtual CENTROSEXTERNOS CENTROEXTERNO { get; set; }

    }
}
