//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using RadioWeb.Models.Clases;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EMAIL
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public int OWNER { get; set; }
        public string USERNAME { get; set; }
        
        [EmailAddress(ErrorMessage = "Email incorrecto")]
        public string CONCOPIA { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }

        [EmailAddress(ErrorMessage = "Email incorrecto")]
        public string DIRECCION { get; set; }
        public string ASUNTO { get; set; }
        public string TIPO { get; set; }
        public string TEXTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IOR_PACIENTE { get; set; }
        public string ADJUNTO1 { get; set; }
        public string ADJUNTO2 { get; set; }
        public string ADJUNTO3 { get; set; }

    }
}
