//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public int OWNER { get; set; }
        public short ORDEN { get; set; }
        public string NOMBRE { get; set; }
        public string CIF { get; set; }
        public byte[] LOGO { get; set; }
        public string BORRADO { get; set; }
        public string DIRECCIO { get; set; }
        public string CP { get; set; }
        public string CIUDAD { get; set; }
    }
}
