//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EXP_CONSUM
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        [DataType("TECNICO")]
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public Nullable<int> IOR_CONSUM { get; set; }
        public Nullable<int> IOR_EXPLORACION { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public string PAGADO { get; set; }
        public string APLAZADO { get; set; }
        public Nullable<int> IOR_ENTIDADPAGADORA { get; set; }
        public Nullable<int> IOR_GPR { get; set; }
        public Nullable<int> IOR_MONEDA { get; set; }
        public string FACTURADO { get; set; }
        public Nullable<int> IOR_FACTURA { get; set; }
        public string PAGAR { get; set; }
        [NotMapped]
        public string SIMBOLO { get; set; }

        [NotMapped]
        public string EXPLORACIONINFORMADA { get; set; }

        [NotMapped]
        public MUTUAS ENTIDADPAGADORA { get; set; }

        public string BORRADO { get; set; }

        [NotMapped]
        public CONSUMIBLES CONSUMIBLE { get; set; }
        [NotMapped]
        public string CODMUT { get; set; }

        public string DOSIS { get; set; }

        public string CABINF_DOSIS { get; set; }

        public string CABINF_DLP { get; set; }

        public string HORA { get; set; }

        //MCI es la dosis del consumible
        public Nullable<double> MCI { get; set; }

        //DLP mGy/cm
        public Nullable<double> DLP { get; set; }

        [NotMapped]
        public List<PAGOS> PAGOS { get; set; }

        [NotMapped]
        public string TECNICO{ get; set; }
    }
}
