//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models.API
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EXPLORACION
    {
        public enum APARATOS
        {
            RESONANCIAMANRESA = 15531680
            
        }
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> CENTRO { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        //Virtual EMPRESA
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string ESTADO { get; set; }
        public string IDENTIFICA { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FECHA_IDEN { get; set; }
        public string HORA_IDEN { get; set; }
        public string HORAMOD { get; set; }
        //Virtual GPR
        public Nullable<int> IOR_GPR { get; set; }
        //Virtual MUTUA
        public Nullable<int> IOR_ENTIDADPAGADORA { get; set; }
        //Virtual PACIENTE
        public int IOR_PACIENTE { get; set; }
        //Virtual APARATO
        public Nullable<int> IOR_APARATO { get; set; }
        //Virtual GPARATO
        public Nullable<int> IOR_GRUPO { get; set; }
        //Virtual APARATO
        public Nullable<int> IOR_TIPOEXPLORACION { get; set; }

    }
}
