//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FACTURAS
    {
        [Key]          
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }  
        public Nullable<System.DateTime> FECHA { get; set; }
        public string COD_PAC { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string CP { get; set; }
        public string CIUDAD { get; set; }
        public string PROVINCIA { get; set; }
        public string EMPRESA { get; set; }
        public string CO1 { get; set; }
        public string CO2 { get; set; }
        public string CO3 { get; set; }
        public string CO4 { get; set; }
        public string CO5 { get; set; }
        public Nullable<double> CA1 { get; set; }
        public Nullable<double> CA2 { get; set; }
        public Nullable<double> CA3 { get; set; }
        public Nullable<double> CA4 { get; set; }
        public Nullable<double> CA5 { get; set; }
        public Nullable<double> EURO_CA1 { get; set; }
        public Nullable<double> EURO_CA2 { get; set; }
        public Nullable<double> EURO_CA3 { get; set; }
        public Nullable<double> EURO_CA4 { get; set; }
        public Nullable<double> EURO_CA5 { get; set; }
        public Nullable<float> IVA1 { get; set; }
        public Nullable<short> IVA2 { get; set; }
        public Nullable<short> IVA3 { get; set; }
        public Nullable<short> IVA4 { get; set; }
        public Nullable<short> IVA5 { get; set; }
        public Nullable<float> SUMA { get; set; }
        public Nullable<double> EURO_SUMA { get; set; }
        public string EURO_P { get; set; }
        public string FAC { get; set; }
        public Nullable<double> NUM_FAC { get; set; }
        public System.DateTime FECHA_FAC { get; set; }
        public string REF { get; set; }
        public string COD1 { get; set; }
        public string COD2 { get; set; }
        public string COD3 { get; set; }
        public string COD4 { get; set; }
        public string COD5 { get; set; }
        public string DNI { get; set; }
        public string TIPO { get; set; }
        public string COD_MUT { get; set; }
        public string COD_FAC { get; set; }
        public Nullable<double> SUMAPAGADA { get; set; }
        public Nullable<double> SUMAPAGAD2 { get; set; }
        public Nullable<double> SUMAPAGAD3 { get; set; }
        public Nullable<double> EUROPAGADA { get; set; }
        public Nullable<double> EUROPAGAD2 { get; set; }
        public Nullable<double> EUROPAGAD3 { get; set; }
        public Nullable<System.DateTime> FECHA2 { get; set; }
        public Nullable<System.DateTime> FECHA3 { get; set; }
        public string HORAMOD { get; set; }
        public Nullable<int> IOR_PAC { get; set; }
        public Nullable<int> IOR_ENTIDADPAGADORA { get; set; }
        public Nullable<int> IOR_GPR { get; set; }
        public Nullable<int> IOR_MONEDA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public string CONTRATO { get; set; }
        public string CODIICS { get; set; }
    }
}
