//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using RadioWeb.Models.Repos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RadioWeb.Models
{
    [Table("GAPARATOS")]
    public partial class GAPARATOS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }

        [Display(Name = "GRUPO")]
        [StringLength(16)]
        [Required]
        public string COD_GRUP { get; set; }

        [Display(Name = "DESCRIPCIÓN")]
        [StringLength(30)]
        public string DES_GRUP { get; set; }
        public Nullable<int> TOT_GRUP { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }

        [NotMappedAttribute]
        public virtual EMPRESAS EMPRESA { get; set; }
    }
}
