//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HUECO
    {
      
        public string IDHUECO { get; set; }
        public string CODIGOAPARATO { get; set; }
        public string FIL_EXPLORACION { get; set; } 
        public string IDLISTA { get; set; }
        public string FECHA { get; set; }
        public string HORA { get; set; }
        public string CENTRO { get; set; }
        public DAPARATOS DAPARATO{ get; set; }
        public int IOR_APARATO { get; set; }
        public int IOR_BOLSA { get; set; }

        public string TEXTO { get; set; }
        
    }
}
