//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDLISTAHUECOSDKV
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string AMBULANCIA { get; set; }
        public string URGENCIA { get; set; }
        public string GRAVEDAD { get; set; }
        public Nullable<int> ALTURA { get; set; }
        public Nullable<int> PESO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string ANESTESIA { get; set; }
        public string CLAUSTROFOBIA { get; set; }
        public string MARCAPASOS { get; set; }
        public string INTERVENIDO { get; set; }
        public string VENDAJE { get; set; }
        public string OTROS { get; set; }
        public string CONTRASTE { get; set; }
        public Nullable<int> IOR_EXPLORACION { get; set; }
        public string TEXTO { get; set; }
    }
}
