//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class IMAGENES
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }

        [DisplayName("TIPO")]
        [DataType("DOCUMENTOTIPO")]
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string DESCRIP { get; set; }
        public string EXT { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TIPO { get; set; }
        public string DISCO { get; set; }
        public Nullable<short> VOLUMEN { get; set; }
        public Nullable<int> IOR_PACIENTE { get; set; }
        public Nullable<int> IOR_EXPLORACION { get; set; }
        public string PATH { get; set; }

        [Required]
        [DisplayName("Nombre")]
        public string NOMBRE { get; set; }
        public string GRUPO { get; set; }

        [NotMapped]
        public string NOMBREPACIENTE { get; set; }
        [NotMapped]
        public string FECHAEXPLORACION { get; set; }
        [NotMapped]
        public string HORA { get; set; }

        [NotMapped]
        public string EXPLORACION { get; set; }


        [NotMapped]
        public bool SOLOLECTURA { get; set; }


        [NotMapped]
        public bool FIRMABLEENTABLET { get; set; }

        [NotMapped]
        public string RUTACOMPLETA { get; set; }
    }
}
