//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using global::ADPM.Common.Web.DataAnnotations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class INFORMES
    {

        
        [Key]
        [HiddenInput]
        public int OID { get; set; }

        [NotMapped]
        [TableColumn(Exclude = true)]
        public string ACTION
        {
            get
            {
                return (OID > -1 ? "Edit" : "Create");
            }
        }

        [TableColumn(Exclude = true)]
        public Nullable<int> VERS { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> CID { get; set; }

        [TableColumn(Exclude = true)]
        public string CANAL { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> OWNER { get; set; }

        [TableColumn(Exclude = true)]
        public string USERNAME { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<System.DateTime> MODIF { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_EMPRESA { get; set; }

        [TableColumn(Exclude = true)]
        public string BORRADO { get; set; }

        [Required]
        public string TITULO { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name ="Fecha")]
        public DateTime FECHA { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "REVISION INFORME")]
        public Nullable<System.DateTime> FECHAREVISION { get; set; }

        public string HORAREV { get; set; }

        [NotMapped]
        public Nullable<System.DateTime> FECHAEXPLORACION { get; set; }

        [TableColumn(Exclude = true)]
        public string COD_PAC { get; set; }

        [TableColumn(Exclude = true)]
        public string ALFAS { get; set; }
        //CUANDO LE ENVIAMOS UN SMS UN PACIENTE INDICANDO QUE YA PUEDE PASAR A RECOGER EL I
        [TableColumn(Exclude = true)]
        public string ALFAS2 { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<double> VISITA { get; set; }

        [TableColumn(Exclude = true)]
        public string HORAMOD { get; set; }

        [TableColumn(Exclude = true)]
        public string HORA { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_PAC { get; set; }

        [TableColumn(Exclude = true)]
        public int IOR_MEDINFORME { get; set; }

        [TableColumn(Exclude = true)]
        public int IOR_MEDREVISION { get; set; }

        [TableColumn(Exclude = true)]
        public string REVISADO { get; set; }

        [TableColumn(Exclude = true)]
        public string PATOLOGICO { get; set; }

        [TableColumn(Exclude = true)]
        public string DURACION { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_TECNICO { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_MODALIDAD { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_SITUACION { get; set; }

        [TableColumn(Exclude = true)]
        public Nullable<int> IOR_TECNICA { get; set; }

        [Display(Name = "Val", Order = 3)]
        [TableIcon(Action = "Test", Controller = "Controller",
           FaIconTrue = "fa fa-check", FaIconFalse = "fa fa-times",
           ColorTrue = "green", ColorFalse = "red")]
        public string VALIDACION { get; set; }

        [NotMapped]
        public string MEDICOINFORMANTE { get; set; }

        [NotMapped]
        public string LOGINMEDICOINFORMANTE { get; set; }

        [NotMapped]
        public string FECHAMAXIMAENTREGA { get; set; }

        [NotMapped]
        public string MEDICOREVISOR { get; set; }

        [NotMapped]
        public string LOGINMEDICOREVISOR { get; set; }

        [NotMapped]
        public string PACIENTE { get; set; }

        [NotMapped]
        public string CENTRO { get; set; }

        [NotMapped]
        public int CENTROOID { get; set; }


        [NotMapped]
        [AllowHtml]
        public string TEXTOHTML{ get; set; }

        [NotMapped]
        public string MOVILPACIENTE { get; set; }

       
    }
}
