//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using global::ADPM.Common.Web.DataAnnotations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    [Table("INFORMESPDF")]
    public partial class INFORMESPDF
    {

        
        [Key]
        [HiddenInput]
        public int OID { get; set; }

        [NotMapped]
        [TableColumn(Exclude = true)]
        public string ACTION
        {
            get
            {
                return (OID > -1 ? "Edit" : "Create");
            }
        }

        public Nullable<int> VERS { get; set; }

        public Nullable<int> CID { get; set; }

        public string CANAL { get; set; }

        public Nullable<int> OWNER { get; set; }

        public string USERNAME { get; set; }

        public Nullable<System.DateTime> MODIF { get; set; }

        public Nullable<int> IOR_EMPRESA { get; set; }

        public string BORRADO { get; set; }

        public string DESCRIP { get; set; }

       
        public string EXT { get; set; }

        public Nullable<System.DateTime> FECHA { get; set; }

        public string TIPO { get; set; }
        
        public string DISCO { get; set; }
       
        public int VOLUMEN { get; set; }

        public int IOR_PACIENTE{ get; set; }

        public string PATH { get; set; }
       
        public string NOMBRE { get; set; }

        public int IOR_EXPLORACION { get; set; }

        public int IOR_INFORME { get; set; }

        public string TIPOEXPLORACION { get; set; }

        public string VALIDACION { get; set; }

        public string MEDINFORME { get; set; }

        public string MEDVALIDACION { get; set; }

       
       
    }
}
