//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LINEAS_FACTURAS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        [Required]
        public string TEXTO { get; set; }
        [Required]
        public Nullable<double> PRECIO { get; set; }
        public string BORRADO { get; set; }
        [NotMapped]
        public int IOR_EXPLORACION { get; set; }
        [NotMapped]
        public string ESTADO { get; set; }

        [NotMapped]
        public int IOR_EXPCONSUMIBLE{ get; set; }
        //ESTO ES UN CAMPO LOGICO QUE USAMOS PARA SABER SI ES UNA LINEA DE CONSUMIBLE
        //O DE EXPLORACION
        [NotMapped]
        public string  TIPOLINEA { get; set; }

        [NotMapped]
        public int INDEX { get; set; }

        [NotMapped]
        public string PACIENTE { get; set; }

        [NotMapped]
        public string FECHA { get; set; }

        [NotMapped]
        public string FECHA_FAC { get; set; }

        [NotMapped]
        public string PERMISO { get; set; }



        [NotMapped]
        public string FACTURADA { get; set; }

        [NotMapped]
        public string AUTORIZACION { get; set; }

        [NotMapped]
        public string SIMBOLO { get; set; }
    }
}
