//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("MUTUAS")]
    public partial class MUTUAS
    {

        public MUTUAS()
        {
            this.DIRECCIONES = new HashSet<DIRECCION>();
            this.TELEFONOS = new HashSet<TELEFONO>();
            
        }

        [Key]
        public int OID { get; set; }

        [Display(Name = "OBSOLETO")]
        [DataType("BooleanInt")]
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }

        [Display(Name = "TIPO")]
        [DataType("MUTUATIPO")]
        public int OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public Nullable<double> CODIGO { get; set; }
        public string NOMBRE { get; set; }
        //este campo esta obsoleto, no usar!!!!!!!!!!!
        public string COD_MUT { get; set; }
        public string COD_CAP { get; set; }
        public string COD_DAP { get; set; }
        public Nullable<short> PREFIJO { get; set; }
        public string NIF { get; set; }
        public string CONTACTO { get; set; }
        public string TRATA { get; set; }

        [Display(Name = "NUMERO CLIENTE")]
        public string NUM_CLI { get; set; }
        public string CODMUT { get; set; }
        public Nullable<int> IOR_DAP { get; set; }
        public string CONTRATOICS { get; set; }
        public string CODIICS { get; set; }
        [Display(Name = "CENTRAL")]
        [DataType("MUTUASLIST")]
        public Nullable<int> IOR_CENTRAL { get; set; }

        [Display(Name = "TIPO PAGO")]
        public string TIPOPAGO { get; set; }

        [Display(Name = "DIAS CARENCIA")]
        public string DIASCARENCIA { get; set; }
        public string MAILING { get; set; }

        [NotMapped]
        public string ACTION
        {
            get
            {
                return (OID > 0) ? "Update" : "Create";
            }

        }

        [Display(Name = "CitaOnline")]
        [DataType("BooleanString")]
        public string CITAONLINE { get; set; }

        [UIHint("DIRECCION")]
        public virtual ICollection<DIRECCION> DIRECCIONES { get; set; }

        [UIHint("TELEFONO")]
        public virtual ICollection<TELEFONO> TELEFONOS { get; set; }

        [NotMapped]
        public string CENTRAL { get; set; }
        [NotMapped]
        public  string TEXTO { get; set; }

    }
}
