//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_APARATOS
    {
        public int OID { get; set; }
        public Nullable<int> OWNER { get; set; }
        public Nullable<int> LAST_VALUE { get; set; }
        public string BORRADO { get; set; }
    }
}
