//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NUM_FACTURAS
    {
        [Key]
        public int OID { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> IOR_GPR { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string ULTIMO_ASIGNADO { get; set; }
        public string BORRADO { get; set; }
    }
}
