//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class P_INFORMES
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORAMOD { get; set; }
        public Nullable<int> IOR_MODALIDAD { get; set; }
        public Nullable<int> IOR_SITUACION { get; set; }
        public Nullable<int> IOR_TECNICA { get; set; }

        //CAMPOS LOGICOS
        [NotMapped]
        public string DESC_MEDICO { get; set; }
        [NotMapped]
        public string TEXTOHTML { get; set; }
        //CAMPOS LOGICOS
        [NotMapped]
        public string GRUPO_APARATO { get; set; }

        [NotMapped]
        public string CUENTAUSOS { get; set; }

        [NotMapped]
        [DataType("ACCIONESDOCS")]
        public string ACCION { get; set; }
        [NotMapped]
        [DataType("STATUSDOCS")]
        public string STATUS { get; set; }
        [NotMapped]
        public string RUTADOCUMENTO { get; set; }
        [NotMapped]
        public string TIPODOCUMENTO { get; set; }
        [NotMapped]
        public int OIDEXPLORACION { get; set; }

    }
}
