//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RadioWeb.Models.API
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Reflection;
    using System.ComponentModel.DataAnnotations;
    public partial class Paciente
    {
        public Paciente()
        {
            Origen = "Manresa";
        }

        public int Oid { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Dni { get; set; }
        public string Sexo { get; set; }
        public string FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string IdManresa { get; set; }
        public string IdEnvio { get; set; }
        public string Origen { get; set; }
        public string Email { get; set; }
        public string IOR_MUTUA { get; set; }

        //OID DEL CENTRO EXTERNO QUE DA EL ALTA
        public int IOR_CENTROEXTERNO { get; set; }

        public string DOCUMENTO { get; set; }


        public Models.EXPLORACION Exploracion { get; set; }
        public List<Models.EXPLORACION> Exploraciones { get; set; }
    }
}
