//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PAGOS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        [NotMapped]
        public string DESCRIPCION { get; set; }
        public string CANAL { get; set; }
        public int OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }

        [Required(ErrorMessage = "Debe especificar la cantidad abonada.")]
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<System.DateTime> DEUDA_FECHA { get; set; }
        
        public Nullable<double> DEUDA_CANTIDAD { get; set; }
        public string APLAZADO { get; set; }
        public string TIPOPAGO { get; set; }
        [NotMapped]
        public string SIMBOLO { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string ACTUALIZADO { get; set; }
        public Nullable<int> IOR_MONEDA { get; set; }

        [NotMapped]
        public EXPLORACION EXPLORACION { get; set; }

        [NotMapped]
        public MONEDAS MONEDA { get; set; }

    }
}
