//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PAGO_PACIENTE
    { 
        [Key]
        public int OID { get; set; }
        public int OWNER { get; set; }      
        public string ORDEN  { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FECHA { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        [DataType("MUTUA")]
        public string MUTUA { get; set; }
        public string EXPLORACION { get; set; }
        public string APARATO { get; set; }
        public string TIPO { get; set; }

        [Required(ErrorMessage = "Precio Obligatorio!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Cantidad Abonada debe ser un número.")]
        public string PRECIO { get; set; }

        [Required(ErrorMessage = "Cantidad Abonada Obligatoria!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Cantidad Abonada debe ser un número.")]
        public string PAGO { get; set; }
        public string MONEDA { get; set; }

        [DataType("TIPOPAGO")]
        public string TIPOPAGO { get; set; }

        [DataType("BooleanString")]
        public string FACTURADA { get; set; }
        
        [Display(Name = "INCLUIR EN FACTURA")]
        [DataType("BooleanString")]
        public String PAGAR { get; set; }

        [DataType("BooleanString")]
        public string PAGADO { get; set; }
        public string NPACIENTE { get; set; }
        public int OIDPAGO { get; set; }

        [NotMapped]
        public PACIENTE PACIENTE { get; set; }

        [NotMapped]
        public int IOR_PACIENTE { get; set; }

        [NotMapped]
        public int IOR_FACTURA { get; set; }


        [NotMapped]
        public string SERIEYNUMEROFACTURA { get; set; }

        [NotMapped]
        public List<PAGO_PACIENTE> PagosExploracion { get; set; }
        public List<PAGO_PACIENTE> ConsumiblesExploracion { get; set; }
        public List<PAGO_PACIENTE> ConsumiblesPagos { get; set; }


     
    }
}
