//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PERSONAL")]
    public partial class PERSONAL
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string BORRADO { get; set; }
        public string NOMBRE { get; set; }
        public string TRATA { get; set; }
        public string COD { get; set; }
        public string NIF { get; set; }
        public string HORAMOD { get; set; }
        public string LOGIN { get; set; }
        public string NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IOR_CARGO { get; set; }
        public Nullable<System.DateTime> FECHAN { get; set; }
        public string DNI { get; set; }
    }
}
