//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PIVOTTABLE")]
    public partial class PIVOTTABLE
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public string  NOMBRE { get; set; }
        public string  DESCRIPCION { get; set; }
        public string IOR_EMPRESA { get; set; }
       public string DATOS { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime?  FECHAINICIO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? FECHAFIN { get; set; }

        public string BORRADO { get; set; }


        //public string APLAZADO { get; set; }
        //r.OID, r.VERS, r.CID, r.CANAL, r.OWNER, r.USERNAME, r.MODIF,
        //r.DESCRIPCION, r.IOR_EMPRESA, r.BORRADO, r.DATOS



    }
}
