//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PRECIOS_CONSUM
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public Nullable<int> IOR_CONSUM { get; set; }
        public Nullable<int> IOR_ENTIDADPAGADORA { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> IOR_MONEDA { get; set; }
        public string BORRADO { get; set; }
        [NotMapped]
        public CONSUMIBLES CONSUMIBLE { get; set; }
    }
}
