//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATION_DEF
    {
        public int RID { get; set; }
        public Nullable<int> VERS { get; set; }
        public int FROM_CID { get; set; }
        public int TO_CID { get; set; }
        public string RELATION_NAME { get; set; }
        public string FIELD_RELATED { get; set; }
        public Nullable<short> DELETE_RULE { get; set; }
    }
}
