//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RX
    {
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public string DENOM { get; set; }
        public string ALT_DENOM { get; set; }
        public string NOM_CLASS { get; set; }
        public string PROCEDIM { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<int> IOR_MONEDA { get; set; }
        public string BORRADO { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public Nullable<int> IOR_ENTIDADPAGADORA { get; set; }
        public string CODI { get; set; }
        public string CODI_NOU { get; set; }
        public string DESCRIPCIO_NOU { get; set; }
        public string LATERALITAT { get; set; }
        public string GRUP_FACTU { get; set; }
        public string SERAM { get; set; }
        public string ICD9 { get; set; }
        public string SNOMED { get; set; }
        public string G_RA_MN_AL { get; set; }
        public string ATENCIA_ES { get; set; }
    }
}
