//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public partial class TABLETAS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }   
        public Nullable<int> OWNER { get; set; }
        public Nullable<int> ORDEN { get; set; }        
        public string CANAL { get; set; }
        public string BORRADO { get; set; }
        public int IOR_CENTRO{ get; set; }
        public string TABLETA { get; set; }
        public string TABLETA_NAME { get; set; }


    }
}
