//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TELEFONO")]
    public partial class TELEFONO
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }
        public string CANAL { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> MODIF { get; set; }
        public Nullable<int> CENTRO { get; set; }
        public Nullable<short> PREFIJO { get; set; }
        public string NUMERO { get; set; }
        public Nullable<int> IOR_EMPRESA { get; set; }
        public string PRE { get; set; }
        public string LOCALIZACION { get; set; }
        [Column("TELEFONO")]
        public string TELEFONO1 { get; set; }
        public string BORRADO { get; set; }
        public Nullable<int> IOR_TIPO { get; set; }

        public virtual MUTUAS MUTUA { get; set; }

    }
}
