//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("VID_RESPUESTAS")]
    public partial class VID_RESPUESTAS
    {
        [Key]
        public int OID { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<int> CID { get; set; }   
        public Nullable<int> OWNER { get; set; }
        public Nullable<int> IOR_CONSENTIMIENTO { get; set; }
        public string PREGUNTA { get; set; }
        public string RESPUESTABOOL { get; set; }
        public string RESPUESTATEXTO { get; set; }

      


    }
}
